### PR TITLE
HM-4694: Announcement banner

### PR DESCRIPTION
**Pull request by dta-tyler**
This pull request adds a site-wide announcement banner.

### CODE REVIEW

**Comment by dta-tyler** [comment]
Content not yet finalised.

**Comment by dta-tyler** [comment]
Content has been reviewed.

**Comment by dta-tyler** [comment]
Hyperlink has been changed to open in same window to follow [W3 accessibility guidelines](https://www.w3.org/TR/WCAG20-TECHS/G200.html).

**Review by dta-tom — APPROVED** [review]
Looks good

**Pull request merged**
